### ISSUE TITLE
editorial: rational for ath unclear

### ISSUE THREAD

**Issue by jogu** [danielfett/draft-dpop#107]
The reason for having `ath` (or perhaps the reason for not having an equivalent claim presented when refresh tokens and authorization codes are used) was a bit unclear to me. Reading the commentary on https://github.com/danielfett/draft-dpop/pull/62 I think explained it (my takeaway was essentially "because access token proofs are exposed in more places" and "it prevents refresh tokens and pre-computed proofs being useful if exfiltrated") - it may be helpful to include some explanation in the document?

**Comment by bc-pi** [comment]
Yeah, I think the rational isn't too clear because the the real value of the ath claim isn't entirely 100% clear either. At least from my perspective. The text at the end of this paragraph https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-04.html#section-2-6 says what you said (more or less) with, "the impact of precomputed DPoP proofs is limited somewhat by the proof being bound to an access token on protected resource access. Because a proof covering an access token that does not yet exist cannot feasibly be created, access tokens obtained with an exfiltrated refresh token and pre-computed proofs will be unusable."  The nonce was introduced in the draft revision after ath was introduced.  And, when used, can better prevent the usefulness of precomputed and exfiltrated DPoP proofs. That paragraph tries to explain that too. I'm honestly not sure what else could be said in the document.

**Comment by jogu** [comment]
Thanks Brian. I had missed/not understood that paragraph.

A perhaps naive question, but should something similar be in the 'security considerations' 'DPoP Proof Pre-Generation' section (or perhaps a new section to avoid adding to the unclearness)?

A slightly related thought is that I think this means long lived dpop access tokens are weaker than Mutual-TLS Certificate-Bound Access Tokens. I'm not sure if it's worth explicitly calling this out as some ecosystems may think about migrating from MTLS to DPoP, with the suggested mitigation of using refresh tokens or nonces?

**Comment by selfissued** [comment]
Could you suggest wording for the Security Considerations text you have in mind, @jogu ?

**Comment by jogu** [comment]
I'd suggest a new paragraph at the end of https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-04.html#name-dpop-proof-pre-generation:

The `ath` claim limits the use of pre-generated DPoP proofs to the lifetime of the access token. Servers that do not support the `nonce` mechanism SHOULD NOT issue long-lived DPoP constrained access tokens, preferring instead to use short lived access tokens and refresh tokens. Whilst an attacker could pregenerate dpop proofs to use the refresh token to obtain a new access token, they would be unable to realistically pregenerate dpop proofs to use a newly issued access token.

**Comment by b---c** [comment]
That second sentence is hard to wrap my head around because there are both AS and RSs that servers that could support or not the nonce mechanism while only the AS issues tokens.

**Comment by b---c** [comment]
maybe with a slight tweak: "The ath claim limits the use of pre-generated DPoP proofs to the lifetime of the access token. Deployments that do not utilize the nonce mechanism SHOULD NOT issue long-lived DPoP constrained access tokens, preferring instead to use short lived access tokens and refresh tokens. Whilst an attacker could pre-generate DPoP proofs to use the refresh token to obtain a new access token, they would be unable to realistically pre-generate DPoP proofs to use a newly issued access token."
