### ISSUE TITLE
Considerations for new authentication schemes 

### ISSUE THREAD

**Issue by ioggstream** [danielfett/draft-dpop#144]
## Considerations for new authentication schemes.

4. we need to add further consideration requested by [rfc 7235](https://datatracker.ietf.org/doc/html/rfc7235#section-5.1.2) 

- [ ] usable in origin-server and/or proxy-auth
- [ ] caching considerations (they are in other parts of the document but not in the authentication scheme section)
- [x] treatment of unknown extension parameters (e.g. must-ignore/must-understand)
- [ ]  defining extension policy (eg. update spec/ use a registry)

## token 68

I have read the discussion on the [ml](https://mailarchive.ietf.org/arch/browse/oauth/?q=token68)
and I wanted to provide some bits to the discussion.

1. iiuc this specification does not describe how to parse access tokens. My understanding is that access token syntax is then irrelevant for the implementation of this specification. OAuth2.1 give space to future implementation stating

``` 
There is no requirement on the particular structure or format of a
 bearer token, as described in Section 5
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-5
```

3. my advice is to leave to the underlying general OAuthX protocol the decision of the token syntax as an interoperability consideration, given that [OAuth2 defines a syntax for Bearer tokens](https://datatracker.ietf.org/doc/html/rfc6750#section-2.1)

**Comment by b---c** [comment]
OAuth 2.0 https://datatracker.ietf.org/doc/html/rfc6750#section-2.1 and OAuth 2.1 https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-05#section-5.2.1.1 both have `credentials = "Bearer" 1*SP b64token`. This draft is intentionally aiming for consistency with that so that the token sending itself is the same other than the scheme name.  But using the better/newer named token68 from RFC7235. That's not gonna change at this point. Actually, as I try to type some kind of response here this, I'm unclear what the intent of this issue is.

**Comment by ioggstream** [comment]
1. token68

> That's not gonna change at this point

Ok.

2.  the other points related to rfc 7235 are still valid. The specification should explicit :

- whether the authorization scheme can be used for proxy-authentication or not
- how the scheme parameters can be updated.- I suppose via another specification since this spec does not define a registry
- the use of caching

**Comment by b---c** [comment]
from again reading https://datatracker.ietf.org/doc/html/rfc7235#section-5.1.2 

> whether the authorization scheme can be used for proxy-authentication or not 

https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-07.html#section-7.1 is specifically only about origin-server authentication using `WWW-Authenticate` and `Authorization`. I figured that was sufficient but can add something about not being used with   `Proxy-Authenticate` or `Proxy-Authorization` header fields. 

> how the scheme parameters can be updated.- I suppose via another specification since this spec does not define a registry

https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-07.html#section-7.1-10.7 is "must-ignore" for the challenge params and additional params aren't applicable to the `Authorization` header due to the intentional use of `token68`. I don't know that more needs to be said. 

> the use of caching

I believe the draft already covers the needed caching considerations.

**Comment by b---c** [comment]
#147
