### ISSUE TITLE
Mention correlation attack

### ISSUE THREAD

**Issue by nikosft** [danielfett/draft-dpop#175]
The JWK included in a dpop proof can be used as a correlation handle if the same key is used with multiple resource servers. I believe section 11 should be extended to include paragraph similar to [that](https://www.rfc-editor.org/rfc/rfc7800.html#section-5)

**Comment by b---c** [comment]
Hi Nikos, 
In in terms of the process, this document has moved out of the working group and is now with the IESG. The bar for making changes at this stage is quite a bit higher.  RFC7800 is a normative reference of this document so that paragraph you linked is effectively included/imported already. That might not be ideal from your perspective but I believe it's sufficient.

**Comment by nikosft** [comment]
> That might not be ideal from your perspective but I believe it's sufficient.

Yes, it makes absolute sense.
