### ISSUE TITLE
Use RFC 7800 "cnf" claim for PoP key representation

### ISSUE THREAD

**Issue by selfissued** [danielfett/draft-dpop#23]
We should use the syntax in https://tools.ietf.org/html/rfc7800#section-3.2 for representation of the PoP key.

**Comment by webhamster** [comment]
Done.

**Comment by b---c** [comment]
This issue and change came about from an erroneous comment* on the list and should be changed back (pending any other changes in who the key and/or proof and/or binding are encoded and transported). 

* some messages from the thread 
https://mailarchive.ietf.org/arch/msg/oauth/BHPP5tnuR4KyEE2ZuKwd5v4Wrr4
https://mailarchive.ietf.org/arch/msg/oauth/LKtMukFLF87wKkG21-OgMIrYgLU
https://mailarchive.ietf.org/arch/msg/oauth/IHt83R7tGwb9iuC9MhPTFIDJrAI

**Comment by b---c** [comment]
Unless this is meant to suggest that `cnf":{"jwk": ... } ` be used rather than a new confirmation method member like `cnf":{"dpop+jwk": ... } `.  The existing `jwk` member in the `cnf` claims syntax per https://tools.ietf.org/html/rfc7800#section-3.2 seems sufficient. I don't see the value in a new `dpop+jwk` variant?  But with all that said, I suspect that we might want to adjust things so that the public key and proof of possession of the corresponding private key is carried in one header (maybe 2 per #26 ?) and the access token be bound to that key via a more concise `cnf` method like `kid` with a JWK Thumbprint as described in the end of https://tools.ietf.org/html/rfc7800#section-3.4 or maybe a new JWK Thumbprint confirmation method.

**Comment by danielfett** [comment]
Why not use the `cnf` claim in the binding JWT? I think I see where you are coming from, but looking at RFC7800, the description of `cnf` fits quite well: 

  > By including a "cnf" (confirmation) claim in a JWT, the issuer of the
  >   JWT declares that the presenter possesses a particular key and that
  >   the recipient can cryptographically confirm that the presenter has
  >   possession of that key.  The value of the "cnf" claim is a JSON
  >   object and the members of that object identify the proof-of-
  >   possession key."

It does not fit for the proof JWT, I think that is clear.

**Comment by b---c** [comment]
When squint just right at the case where the issuer and presenter are the same the `cfn` description can be read to fit. However, I'd argue that's really not in line with the intent of RFC7800. 

Even in the case of the binding JWT, the token is being sent and somewhere the verification key is being communicated to. That could be jammed in the `cnf` claim but a JOSE header is the more appropriate and straightforward place for indicating the key that was used to sign (can be used to verify). The `jwk` header for example, is exactly that https://tools.ietf.org/html/rfc7515#section-4.1.3 and is meta information about the JWS where it logically belongs:. 
```
4.1.3.  "jwk" (JSON Web Key) Header Parameter

   The "jwk" (JSON Web Key) Header Parameter is the public key that
   corresponds to the key used to digitally sign the JWS.  This key is
   represented as a JSON Web Key [JWK].  Use of this Header Parameter is
   OPTIONAL.
```

It may well be moot, however, as the discussions in #26 seem to be moving towards combining the proof and binding concepts into one thing and moving the JWK out of the token.

**Comment by selfissued** [comment]
Brian has largely convinced me that my original comment was wrong and we should use the "jwk" header parameter, since we're representing the key signing the JWT.  (Yes, it's also a PoP key.)

**Comment by danielfett** [comment]
I agree, `jwk` fits much better. Moving back to `jwk`.
