### ISSUE TITLE
Add syntax for using DPoP with the implicit flow

### ISSUE THREAD

**Issue by selfissued** [danielfett/draft-dpop#37]
In conversations with @ve7jtb and @danielfett at IIW, I communicated that Microsoft also needs syntax for using DPoP with the implicit flow.  John said that all should be required is a syntax for passing the PoP key in the authorization request.  He suggested doing so via a signed OAuth request.

**Comment by tlodderstedt** [comment]
I would like to see a full review of the security and functional implications. As far as I see standard JAR would require the implicit client to register the key via dynamic client registration upfront.

**Comment by jricher** [comment]
I am not convinced that extending this to be used with implicit is a good idea. If there is value in using a key-bound access token with the implicit flow, it should be tied to JAR, JARM, and related mechanisms instead.

**Comment by dwaite** [comment]
I too would like to see a review of the security implications. In particular, I'd like to understand if there is a set of recommendations leveraging DPoP that allow for implicit to meet the requirements of the draft security BCP. 

Since DPoP is primarily being created to allow more clients to meet those requirements, I don't see the point of defining additional logic for implicit unless that gives implicit a defined (and documented) path over the line.

Full disclosure, I also selfishly prefer the discussion around discouraging implicit to stay with the security topics BCP, rather than being around the browser apps BCP. There are still plenty of reasons to recommend against implicit as a practice in the browser apps BCP, even if it can be altered to meet security requirements,

**Comment by danielfett** [comment]
Note that this mechanism has subtly different security properties than DPoP+code. For example, if an implicit client re-uses the DPoP key, a leaked AT can be used by the attacker through access token injection. (The signed OAuth request does not protect against access token injection.)

**Comment by b---c** [comment]
This came up during the IETF105 meeting https://datatracker.ietf.org/doc/minutes-105-oauth-201907261000/ and the thinking/discussion at that time was that it could/should be done in a separate draft, if the WG adopts DPoP.

**Comment by panva** [comment]
> This came up during the IETF105 meeting [datatracker.ietf.org/doc/minutes-105-oauth-201907261000](https://datatracker.ietf.org/doc/minutes-105-oauth-201907261000/) and the thinking/discussion at that time was that it could/should be done in a separate draft, if the WG adopts DPoP.

@selfissued submitted such draft https://datatracker.ietf.org/doc/draft-jones-oauth-dpop-implicit/

**Comment by b---c** [comment]
closing this out as https://datatracker.ietf.org/doc/draft-jones-oauth-dpop-implicit/ has been submitted by @selfissued
