### ISSUE TITLE
Backwards-Compatibility of DPoP

### ISSUE THREAD

**Issue by danielfett** [danielfett/draft-dpop#41]
Should DPoP be usable by a client even if the AS/RS do not support it?

DPoP is currently designed such that it can be used by a client even if the AS/RS do not support DPoP. To this end, the client adds headers that do not interfere with a normal operation of the AS/RS. The client can observe (via the `token_type=Bearer-DPoP` value) whether the particular AS supports DPoP. There is no way of knowing whether the RS supports DPoP. The current approach requires that, in order to be backward-compatible, the access token type sent to the RS is `Bearer` (in the `Authorization` header). This is not a clean design for two reasons: 1. The token type communicated by the AS to the client is `Bearer-DPoP`, not `Bearer`. 2. The token is not actually a `Bearer` token, since the client needs to prove possession of a key.

I see three potential solutions:

1. Do away with the backwards compatibility. DPoP introduces a new token type and we use that token type in the `Authorization` header. We could optionally add the DPoP-Proof into that header as well. If a client receives a `token_type=Bearer` response from the token endpoint, it could switch DPoP off or abort the transaction.
2. Get rid of the new token type and still call it a `Bearer` token. Potentially create another way for the Client to learn whether the AS/RS supports DPoP, either via a new parameter or via metadata.
3. Keep the current, inconsistent, state of affairs.

I strongly favor Option 1.

**Comment by tlodderstedt** [comment]
+1 for option 1

**Comment by danielfett** [comment]
@mengan Would Option 1 work for you?

**Comment by panva** [comment]
> The token is not actually a Bearer token, since the client needs to prove possession of a key.

Wouldn't the same apply to [`Mutual TLS Client Certificate-Bound Access Tokens`](https://tools.ietf.org/html/draft-ietf-oauth-mtls-14#section-3)? IIRC Mutual-TLS spec went the route of option 2, not sure if this was discussed or not but no language in the draft specifies a new token type.

@b---c, thoughts?

**Comment by danielfett** [comment]
> > The token is not actually a Bearer token, since the client needs to prove possession of a key.
> 
> Wouldn't the same apply to [`Mutual TLS Client Certificate-Bound Access Tokens`](https://tools.ietf.org/html/draft-ietf-oauth-mtls-14#section-3)? IIRC Mutual-TLS spec went the route of option 2, not sure if this was discussed or not but no language in the draft specifies a new token type.

I heard that the reasoning was that MTLS works (mainly) on a different layer. On the application layer, the usage of the token does not change. Still, in the overall picture, MTLS-bound tokens are not Bearer tokens, but to spare existing implementations from changing too much code, Bearer was kept.

Somebody correct me if I'm wrong.

**Comment by panva** [comment]
But even for mtls the RS has to adapt as it needs to calculate the cert thumbprint for comparison. 

And the clients have to as well. I rarely see mutual-TLS applied to clients making the https calls automatically.

**Comment by danielfett** [comment]
> But even for mtls the RS has to adapt as it needs to calculate the cert thumbprint for comparison.

I agree. But it seems to be a compromise that we do not have to make.

**Comment by danielfett** [comment]
Also, `Bearer-DPoP` does not make too much sense. If we take option 1, I would call the `token_type` just `DPoP` or similar.

**Comment by b---c** [comment]
MTLS did take the option 2 route for a variety of reasons but mostly because it seemed like it would make implementations easier and adoption/migration more straightforward. I think that has largely proven to be true. 

There are tradeoffs either way though and to me anyway, it's not obvious what route would be 'best' for DPoP.

**Comment by paulquerna-okta** [comment]
Just throwing out a different path based on the comments above.

1) Add must depend on https://tools.ietf.org/html/draft-cavage-http-signatures-11
2) Add should depend on https://tools.ietf.org/html/draft-ietf-oauth-resource-indicators-02

Reflow roughly as follows:
1) Client to AS: Send HTTP Signature for Token Request and adds new oauth parameter with JWK indicating dpop.

2) AS validates HTTP Signature based on oauth parameter, policy, etc.
  - (optional / should) Based on resource indicator and policy, decide if Resource Server supports DPoP.
  - (must) Add `cnf` claim to Access Token with the JWK
  - `token_type` is DPoP

3) Client to Resource:
  - Add new key, "access_token" to HTTP Signature parameters
  - Sign Request as in http-signatures, optionally using the `signature_headers` hint.

4) Resource extracts `cnf`  from `access_token` param to HTTP  Signatures.  Validates Access Token, then validates whole Signature.  If the Resource wants a different list of `signature_headers` than the client sent, prompt with WWW-Authenticate as http-signatures covers.

**Comment by dwaite** [comment]
I would push for option 1. 

To limit access token leakage at a resource server an AS would want to either

  a. Have the client request tokens restricted by audience (possibly via resource indicators)
  b. Have the client use proof of possession

We need resource servers to fail if they don't support DPoP so we can require audience restriction instead. An AS policy might even send opaque access tokens to resources only supporting bearer, so that the introspection endpoint can enforce audience verification.

We also would prefer resource servers to be able to communicate their capabilities in their 401 responses. For example, `WWW-Authenticate: DPoP` and `WWW-Authenticate: Bearer` sent on the same response would indicate the resource supports both modes.

A client supporting DPoP may try it against an AS and resources, negotiating bearer tokens if it hits a compatibility problem. (Ignoring for now the issues with managing multiple access tokens, which we already have with audience constraints)

**Comment by mengan** [comment]
good evening, 

sorry for the delayed response. (busy catching back up from IIW)

So I believe that the Access_token is still a bearer token.  It contains an Additional attribute (dpop+jwk) but as a whole that token is usable as a bearer. 

It is ONLY the dpop header that is actually a binding. so I don't believe leaving the access_token as a bearer is wrong. 

Second, there are many libraries that have not yet implemented support for dpop, these libraries may break rather than function when the access token is not a bearer. I realize this is a bad excuse to stay with a legacy value. but consider that few clients will be able to roll out dpop bindings on all interfaces at once. So in order to support something other than bearer a client would expect to need Two access tokens. (one at+jwt . with dpop+jwk,  and one at+jwt without dpop+jwk).   This way the client can pick which token to use for which resource.   but as earlier suggested it's not clear that a client will know which resource servers support or don't support dpop bindings. 

If you ask me what will help push for adoption, then leaving the access_token as bearer will make it Easier for developers to adopt.  but call the dpop header a binding rather than bearer.

**Comment by danielfett** [comment]
I am going for Option 1 for now. It is not a Bearer token, and this is exactly why token_type was introduced in the first place. 

@mengan I do not fully understand your argument here. If a client library does not bring support for DPoP, it just does not send the DPoP header and everything will work as before. 

@paulquerna-okta To keep this simple to implement, we want to keep HTTP signatures out of this standard for now.
