### ISSUE TITLE
uniqueness requirements on jti 

### ISSUE THREAD

**Issue by b---c** [danielfett/draft-dpop#47]
The comment thread on issue #32 veered into discussion of the use of `exp` vs `iat` and was closed to "continue the discussion in #38". However, I believe the original problem in issue #32 is still a potential complication so this is a new issue to track it.

https://tools.ietf.org/html/draft-fett-oauth-dpop-02#section-9.1 has:
>    Furthermore, the "jti" claim in each [DPoP proof] JWT MUST contain
>    a unique (incrementing or randomly chosen) value, as proposed in
>    [RFC7253].  Resource servers SHOULD store values at least for the
>    time window in which the respective JWT is accepted and decline HTTP
>    requests by clients if a "jti" value has been seen before.

The "(incrementing or ...)" part might be problematic and lead to collisions and false positives on replay checks is `jti` alone is what is stored and checked server side when multiple clients (even instances of clients) are incrementing from the same or similar values for jit. The server would need to track `jti` values qualified by the public key or a hash thereof or something like that. And I'd think at that point it'd be easier to just say to track the whole JWT (or a hash thereof) for replay prevention.

I found the reference to RFC7253 not to be helpful. We are talking about nonce like things in both but the context is pretty different as is the scope of uniqueness and the consequences of repetition.  I highly suspect that a developer looking at OAuth and DPoP will not be happy with a reference to the whole document on "The OCB Authenticated-Encryption Algorithm" as advice about setting `jti` claim values.

I would suggest dropping the "incrementing" part for `jti` guidance and rather have a minimum suggested or required entropy to ensure that the likelihood of collisions is approaching zero. Probably 128 bits is good enough - i.e. 16 secure pseudorandom bytes that are base64url encoded gives something like "jti": "_ltc11acc9_ESC4bwc3u-8".

A client could start a series of requests with a pseudorandom jti and increment each subsequent one from there. The doc could mention that. But, as I read it anyway, "incrementing" in the doc now suggests that a client could start from 1 and count up. Which would likely lead to problems.

**Comment by danielfett** [comment]
I agree, the current wording is not correct/helpful. Could you please prepare a pull request for this?

**Comment by b---c** [comment]
Sure thing, I can do that probably next week.

**Comment by tlodderstedt** [comment]
Is unpredictability an important property of the jti? In any case, the AS should treat the client id as namespace for jti values.

**Comment by b---c** [comment]
> In any case, the AS should treat the client id as namespace for jti values.

The client id might not always be available, like in resource access. And also might not be suffienct as a namespace like qualifier when here are multiple instances of a public client using the same client id (SPA or mobile app for example).

**Comment by tlodderstedt** [comment]
Good points. This leaves the uniqueness burden with client and UUIDs as only option?

**Comment by b---c** [comment]
I think there are a number options. The ones that come to mind are:

1) servers track only the jti value and require that jti be globally unique (a UUID or >= ~128 bit random)
2) servers track the public key (or hash of it) + a jti that is incrementing or otherwise unique within that instance of the client (like random >= ~32 bits but I'm not sure and it really depends on how many requests are being made in the allowed timeframe to the same URI/method)
3) servers track the whole dpop jwt (or probably a hash of it) and jti is not required at all (or could be very very small). I think the iat and jwk and signature in the dpop jwt would provide more than sufficient entropy for this to work. Although I guess multiple requests to the same URI & same method during the same second (iat) when using a deterministic signature scheme would need to be differentiated somehow.     

I think 1 is the most straightforward to describe in a document. I'm drawn to 3 because it would allow for smaller dpops and move some of the complexity burden from the client to the server. 2 kinda does also but feels to me like not a great compromise that's maybe harder for both parties to implement. 

Thoughts? Preferences?

**Comment by b---c** [comment]
I'm gonna just do a PR with option 1.

**Comment by dwaite** [comment]
Option 3 is clever in that it *would* allow clients to omit JTI, and simplifies the resource side - but clients might see intermittent failures from resource servers if they do so. That would depend factors such as how fast they were making requests, IAT accuracy, and crypto algorithm used - the random ‘k’ in ECDSA can serve the purpose of JTI.

None of that means it's “wrong”, just that it is more complex to describe. Including JTI could be a “SHOULD”, but describing *how* to implement a client that omits it will be nuanced/complicated. On the bright side, resources don’t care one way or another - they just hash the value, and reject clients who are doing it wrong.

Option 1 is simple and doesn’t seem to have any exploits, since a behaving client should be providing those values uniquely to a single resource server. If a client tries to use a counter instead of a UUID, it will likely fail quickly. 

Option 2 (using an access token uniqueness value with IAT and/or JTI from the DPOP token) to me seems the least appealing option - it is harder for the resource server to process than option 1, and you eliminate the option of ‘k’/‘iv’ values being used as a per-token randomness. You still have the same or more complexity if you explained to clients how securely minimize/eliminate JTI. 

In any case, values need to be retained for checking as long as the DPoP token itself would have been considered acceptable - not necessarily the full lifetime of the access token. You might also recommend retaining a hash even in case of option 1/2, to at least be a bit more resilient to the obvious memory exhaustion attack on the resource server of stupidly-large DPOP JTI values.

**Comment by danielfett** [comment]
I like Option 3, as most of the work is then done by the server, not the client. The client may use a simple incrementing jti to avoid duplicates. Generating randomness is still somewhat hard and developers might come up with creative solutions to avoid it.

**Comment by tlodderstedt** [comment]
Can't we just recommend a certain UUID version?

**Comment by b---c** [comment]
Hrm... I honestly really like option 3 too. Perhaps I'll take a stab at updating the PR to reflect that.  It'll be a little more complicated to describe but I think for most actual implementations it'll be simpler and more size efficient.

**Comment by b---c** [comment]
Pull request #51 has been updated to be option 3.

**Comment by danielfett** [comment]
After some testing, I do not like Option 3 any longer ;-)

It turns out that JWT decoders/parsers/verifiers give some leeway on the encoding of the JWT. This leads to situations where an attacker can take a signed JWT, modify its representation (and therefore, its hash), and the signature will still verify. Since the hash is different, our Option 3 would not prevent replay of the JWT.

## Example 1 (jwt.io)
Using jwt.io, the following JWT verifies using the secret `secret`:
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.XbPfbIHMI6arZ3Y922BhjWgQzWXcXNrz0ogtVhfEd2o
```
The following JWT with added whitespace, however, also verifies:
```
   eyJhbGc iOiJIUzI1NiIsInR5c CI6IkpXVCJ9 . eyJzdWIiOiI xMjM0NTY3O DkwIiwibm FtZSI6I kpvaG4gRG9lIiwiaW F0IjoxN TE2MjM5MDIyfQ  .XbPfbIHM   I6arZ3Y92 2BhjWgQzWX cXNrz0 ogtVhfEd2o
```
That might be due to some input normalization applied to the web form, so let's look further...
## Example 2 (python pyjwt)
Using pyjwt, an arbitrary number of `=` can be appended to the string:
```
>>> import jwt
>>> encoded_jwt = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')
>>> encoded_jwt_2 = encoded_jwt + b'=='
>>> jwt.decode(encoded_jwt_2, 'secret')  # jwt.decode also verifies the signature
{'some': 'payload'}
>>> encoded_jwt_2 = encoded_jwt + b'===='
>>> jwt.decode(encoded_jwt_2, 'secret')
{'some': 'payload'}
```
## Example 3 (php firebase/php-jwt)
This library eats whitespace and equal signs at the end of the string:
```
<?php
require __DIR__ . '/vendor/autoload.php';
use \Firebase\JWT\JWT;

$key = "example_key";
$token = array(
    "iss" => "http://example.org",
    "aud" => "http://example.com",
    "iat" => 1356999524,
    "nbf" => 1357000000
);

$jwt = JWT::encode($token, $key);
print_r($jwt);
echo ("\n");
print_r(JWT::decode($jwt, $key, array('HS256')));

$jwt2 = $jwt . "====";
print_r($jwt2);
echo ("\n");
print_r(JWT::decode($jwt2, $key, array('HS256')));

$jwt3 = $jwt . " ";
print_r($jwt3);
echo ("\n");
print_r(JWT::decode($jwt3, $key, array('HS256')));

$jwt4 = $jwt . "x"; // negative test
print_r($jwt4);
echo ("\n");
print_r(JWT::decode($jwt4, $key, array('HS256')));

```
Creates the following output:
```
~/tmp/jwthashing$ php test.php
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9leGFtcGxlLm9yZyIsImF1ZCI6Imh0dHA6XC9cL2V4YW1wbGUuY29tIiwiaWF0IjoxMzU2OTk5NTI0LCJuYmYiOjEzNTcwMDAwMDB9.KcNaeDRMPwkRHDHsuIh1L2B01VApiu3aTOkWplFjoYI
stdClass Object
(
    [iss] => http://example.org
    [aud] => http://example.com
    [iat] => 1356999524
    [nbf] => 1357000000
)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9leGFtcGxlLm9yZyIsImF1ZCI6Imh0dHA6XC9cL2V4YW1wbGUuY29tIiwiaWF0IjoxMzU2OTk5NTI0LCJuYmYiOjEzNTcwMDAwMDB9.KcNaeDRMPwkRHDHsuIh1L2B01VApiu3aTOkWplFjoYI====
stdClass Object
(
    [iss] => http://example.org
    [aud] => http://example.com
    [iat] => 1356999524
    [nbf] => 1357000000
)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9leGFtcGxlLm9yZyIsImF1ZCI6Imh0dHA6XC9cL2V4YW1wbGUuY29tIiwiaWF0IjoxMzU2OTk5NTI0LCJuYmYiOjEzNTcwMDAwMDB9.KcNaeDRMPwkRHDHsuIh1L2B01VApiu3aTOkWplFjoYI 
stdClass Object
(
    [iss] => http://example.org
    [aud] => http://example.com
    [iat] => 1356999524
    [nbf] => 1357000000
)
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9leGFtcGxlLm9yZyIsImF1ZCI6Imh0dHA6XC9cL2V4YW1wbGUuY29tIiwiaWF0IjoxMzU2OTk5NTI0LCJuYmYiOjEzNTcwMDAwMDB9.KcNaeDRMPwkRHDHsuIh1L2B01VApiu3aTOkWplFjoYIx
PHP Fatal error:  Uncaught Firebase\JWT\SignatureInvalidException: Signature verification failed in /home/danielf/tmp/jwthashing/vendor/firebase/php-jwt/src/JWT.php:112
```

**Comment by panva** [comment]
Putting aside any input normalization, due to the use of base64 it is the case that the last three octets of the signature may be changed and still lead to valid signature in some cases (examples will follow)

I’d stick to option 1 - require jti

**Comment by panva** [comment]
```js
const jose = require('@panva/jose')

const jwk = jose.JWK.asKey({
  e: 'AQAB',
  n: 'v86-hsjQuZSnKvecqgG7No1rmp_cSI4VfTuq8-RNSz_lvhuXRwvZlR1qjweWLlvXRIo1coMy4MHhmXR23AImWkf4xfWMMmi8lG4cBnf1f-izIXflOpZ2huT9aN4Re4opihROjv0PjSmJKXppIENVmvMIWiM5-X-RCMXKznmF-HgdLYO18-E3_IXR08XDaW-XpM_-SHqFD05lDKNhkWVFkg9LgFbB-EX0H-TphJ-fmlNa8HPb9Hev9vct-mvtsMoH5YQlvgWxlTv7fxHPXuAQD7M7jomjyygDnpPP0fZAlV6tDGN4D_HrwPH8H7E85PKkSCfFEpUtpw8FC4lINj98rw',
  d: 'kuxyI1rGD7Hfz1j2x38mAeaYS0wy99zmdxRyofn6fy7F9Da8TW61T7TFwCQGlSJCpjzcLghzu5ioD90XgvWenT9OP40UxDRYZ7Zkf0v6YO1F8dgeXh-NUU0tE9wvNhuiMCPX_U25UN9FMuGSj2UkuNl7R1h-ezCNT1P7QufxiF5d_iO4vgYElfZ7qM8PNywW0llg6kip4hcipCbMPjHOc3u_6PUKvrMbyHFtyNiJlGpcswbSKQ3GnBHXKXW3V7xipRajB0lrlNuwMAPcDuOvVquvzFMCFol4uZuLyPsi4duaJRlF-XHZWKl54X-QWFoT_jpiqpnCKFNdLQ8tVtTC0Q',
  p: '5detI9sE9jV9iuDoEcNMbqGlDxerz-pkcTdFOtLD8q2P29h2iP_pysntFKXsnhO5i2-a9SJZFDYYbul_IzunBv0l0Gbty6oelYRz1UK6AwN-IoAuxeV5z2mfqUN42Zsfix3t-v6c7pv6VWbTxhsOmLv-gAVg-GvTFxFNArvKsrk',
  q: '1aLxriP7ze_0maAaQBjjzIfcXCIL6oGxr5sVVrNMgCJEWz_Cdp_alKmEaIT6HHjGwHprU-ZURvrnvE-T-p1sll8iaJYLXT19pBenRePKT08L4uzBXVihbFoY2tTZGidRkTWN1Uur0bBfkjo04BaxNNjHfhG0YpX-Ch1HA5ZxFqc',
  dp: 'KZVQxOjuR-E7mnHAat5LqMRkCYv90LsWewlF5DOXsgNGwL60C2tJkB_iXdb7LUpiSmDhxzH0rdxvpTlngCddu7z3J3JH2Y4oxGJXVqEg6ESsgG9yhulSlX0FnukPJ0eSeGfs03lXSTA9JVBaRkBE7sssa1sNxUQ0x7qglTsGnDk',
  dq: 'lGX_o4tzWnYYXq6MDYI8mtK1C3rK9DbrCqSbigI6Xbdv7EK5_lTELQgj5caZRjXPOdzPuRQB7txTJMfSbv_zcfDbofK4KiiQoe-cTjwRSE4MX7E-EG2ElBNxuHCp7jTpwAiHYWaTD7GIcbblC9Q3fBIpYTVDLEgskzILJj7Wh3k',
  qi: 'skBApJqSkOyk5f6Xo9GT9PbiRXo7A1xdI9BLYGVSo0tnmaS4Kz8EMGB89s5X0ppKgdeeosMA7629PcMwYImbBa0Zijfx2m2duvrIeqRw-likiFCRiEsLGVJ8QFfGVFzxTYjlrSI9I9TGJOv5jBxGH5tS1_UgSkybkqiEUUi2eyE',
  kty: 'RSA'
})

const jwt = jose.JWT.sign({ foo: 'bar' }, jwk)
console.log(jwt)
// eyJraWQiOiJqNUpVY1Q5LXJDODF5TWpINWx3SFFKMjhwc0RRaUxKbFdHNlBJT3pMVzBBIiwiYWxnIjoiUFMyNTYifQ.eyJmb28iOiJiYXIiLCJpYXQiOjE1Njk0ODQyMzV9.nVAyA8rLUt7MNZxhNjNofZ3M4AZQ74CM_aVWQENlJ4JsNe_wP9HLQKx56pCjUY5GPOgQdusXvGOLZkTr0e-B12zM8JmEqSFNiInmijOAWx4mG6eD2plJBWDDKHCP9z5syjIcBhTtWDFMqEZa446S-W3HIR-n-JmBqGS7YNS_al6Go-bjZevv6OsiSaAZI2FMC3vcn9Wve-kTbvUrzFhj-e4iTx5qQinVNPfN-1FJmq6D4zzVPKJE0FxYCupHZQWOgLB2H2Wdv0APeJpS6JZvkm-wxyWL86Mo11FduhkO6IFiCUwWRmCyBH3Z830cFMhh_Fz94sY_Exdp9vVQ7QtW6Q

const modified = 'eyJraWQiOiJqNUpVY1Q5LXJDODF5TWpINWx3SFFKMjhwc0RRaUxKbFdHNlBJT3pMVzBBIiwiYWxnIjoiUFMyNTYifQ.eyJmb28iOiJiYXIiLCJpYXQiOjE1Njk0ODQyMzV9.nVAyA8rLUt7MNZxhNjNofZ3M4AZQ74CM_aVWQENlJ4JsNe_wP9HLQKx56pCjUY5GPOgQdusXvGOLZkTr0e-B12zM8JmEqSFNiInmijOAWx4mG6eD2plJBWDDKHCP9z5syjIcBhTtWDFMqEZa446S-W3HIR-n-JmBqGS7YNS_al6Go-bjZevv6OsiSaAZI2FMC3vcn9Wve-kTbvUrzFhj-e4iTx5qQinVNPfN-1FJmq6D4zzVPKJE0FxYCupHZQWOgLB2H2Wdv0APeJpS6JZvkm-wxyWL86Mo11FduhkO6IFiCUwWRmCyBH3Z830cFMhh_Fz94sY_Exdp9vVQ7QtW6W' // <- replaced last character from Q to W

console.log(jose.JWT.verify(modified, jwk))
// { foo: 'bar', iat: 1569484235 }
```

**Comment by panva** [comment]
@danielfett reason why libraries often accept trailing padding and invalid encodings or whatever have you is that there are actually major tech players out there who claim they produce JWT and in fact are producing abominations. The biggest offender is AWS, first they used base64 instead of base64url, then they started using base64url but left the padding.

Library maintainers are getting heat from users since they can't validate JWTs from AWS and finally implement lax behaviours when it comes to the JWT format.

Sad. But true. [`@panva/jose`](https://github.com/panva/jose) for one will reject tokens with padding, whitespace or invalid encoding. What it will not reject since it would mean re-encoding every single JWT part is the above i've shown.

**Comment by danielfett** [comment]
@panva That does not come as a surprise. In fact, I started researching this because I *expected* implementations to behave that way. 

Digging into the python implementation pyjwt, I found that the reason in this case is not to accept invalid encodings, but the use of a certain standard library function that ignores superfluous `=` at the end of the string.

**Comment by b---c** [comment]
Ugh, right. I was just explaining to someone recently about how 'non-meaningful' modifications to the encoding could still still result in a valid token. So I really should have realized that option 3 wouldn't work as-is :/

Before we throw it out completely though - how about option 3 but using just the binary JWS Signature (or hash thereof) as the value to track for replay prevention?

**Comment by panva** [comment]
I think its a lot of caveats already

- clients must use random or incrementing jti value IF using deterministic alg
- servers must check hashes of binary signatures

It's getting to a point where implementers (both sides) will get it wrong compared to a simple `jti` which in a browser is simple to get with webcrypto's `getRandomValues`

**Comment by b---c** [comment]
I take your points there @panva but am still a bit torn.  I don't view tracking the binary signature as any more difficult than tracking a `jti` - it's just a different piece of data from the token. But maybe I'm giving too much credit to the mythical average developer. 

Determining if a deterministic alg is being used is a tricky caveat. Although ECDSA and RSA-PSS are not by default and it just feels so wasteful to require all these `jti`s when they otherwise wouldn't be needed most of the time.

**Comment by panva** [comment]
as a sidenote - for the uninitiated there's no repository of "is this alg deterministic", the term itself does not even show up in the JWA spec (rfc7518). So even if we were to go that route algorithms need to be listed or a different description needs to be given.

**Comment by b---c** [comment]
or an enterprising developer could sign the same thing twice and see if the result is the same

**Comment by panva** [comment]
well, we know that :) an "average" developer might not

**Comment by b---c** [comment]
But maybe `jti` option 1 is sufficiently more straightforward compared to the others that we should just go with that... 

Unfortunately for me, that means reworking some things in two different pull requests.

**Comment by b---c** [comment]
reverted the branch behind the pull request #51 so it once again reflects option 1

**Comment by danielfett** [comment]
It seems that Option 1 is a pretty clear winner here. Let's go for that.
