### ISSUE TITLE
Normalization of URIs might break DPoP

### ISSUE THREAD

**Issue by danielfett** [danielfett/draft-dpop#49]
As Nat pointed out, trailing slashes that are removed by a web server automatically might break the signature in DPoP. Other problematic cases include double slashes and internally rewritten requests.

An approach to tackle this problem might be to include the URI that was signed by the client in the DPoP proof. This way, the AS/RS can apply whatever custom normalization/rewriting logic they like before checking the signature.

**Comment by panva** [comment]
> An approach to tackle this problem might be to include the URI that was signed by the client in the DPoP proof. This way, the AS/RS can apply whatever custom normalization/rewriting logic they like before checking the signature.

The RS/AS does not recalculate the signature and it already has access to the signed value inside the DPoP proof. I think we just need to consider trailing slashes on the recipient side.

It is true that different web frameworks will treat the "current request URL" differently when it comes to trailing slashes, some will normalize, some won't.

A solution is to either 

1) forbid/force trailing slashes on both DPoP Proof producer and recipient side
2) be lax about it and have the recipient accept both - `htu` equal to current URI with or without trailing slash

**Comment by danielfett** [comment]
Since we're including the full URI in the DPoP proof, we don't have this issue any longer.

**Comment by panva** [comment]
@danielfett please see my comment above, I think at least trailing slashes after domain name are a very special case that might be worth calling out. 

Albeit unlikely, an `htu` like `https://rs.example.com` it is still technically possible. And since `https://rs.example.com == https://rs.example.com/` from a routing perspective server developers are left at the mercy of their web frameworks about how these interpret the "current url" for calls to such routes.
