### ISSUE TITLE
SPA recommendations

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#50]
As sent [earlier](https://mailarchive.ietf.org/arch/msg/oauth/X9ri78a9M7Tezo7Kl7Nq4_cyBsk) via the mailing list.

I don't know if this belongs to the DPoP document itself or each respective BCP (especially Browser-Based Apps), but one of the documents should give recommendation to implementers on how to

   1. generate the unique private keys per installation / browser session
   2. platform specific storage for them (e.g. in between browser navigation / app launches)

I come asking for this guidance especially for the Browser-Based App use case. I think the clear recommendation is to use the [Web Cryptography API](https://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-method-generateKey) (with extractable: false) for (1) and [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) for (2), but the more important question is how to deal with lack of those APIs in browsers that are known to not support them or be buggy (see data in https://caniuse.com), so

   - is it ok to use other means of generating the key when webcrypto is not available?
   - is it ok to generate keys through webcrypto (or other means) that are extractable and store them via other means than IndexedDB when indexed DB is not available, such as cookie or localstorage.

**Comment by danielfett** [comment]
I think that implementation guidelines would be useful in the BCP. Can I ask you to propose language on that topic?

**Comment by panva** [comment]
I would love to but i don’t have an answer to the bottom two questions.

**Comment by danielfett** [comment]
I feel like the answers to that very much depend on the implementation. I am also not sure if we want to be **that** detailed in the RFC. But providing generic advice on using WebCrypto for DPoP would make sense.

**Comment by dwaite** [comment]
I don't believe there are any *maintained* browsers that do not support non-exportable keys and IndexDB storage, although you may have to do a little massaging with shim scripts.

Since an unmaintained browser likely has other avenues for script injection and exfiltration, the protection would just to prevent resources leaking or reusing bearer tokens. So, I think it becomes an administrator choice. They can either have DPoP be used with a pure javascript implementation and exportable keys, or support the client running without DPoP and then audience/resource-scope the tokens down.

I will say that there is no dynamic hint from the client that the ephemeral key was generated exportable (so that the AS might decide to adjust its token policies.) The AS may want to determine browser capabilities so that it limits token lifetime or scopes.

**Comment by panva** [comment]
I've published an ESM module for the browser https://www.npmjs.com/package/dpop. I've intentionally left out the storage part. As David pointed out, today's browsers do support IndexedDB but its orchestration should be left up to the implementer. The module will help with the generation of the DPoP Proof JWTs.
