### ISSUE TITLE
preventing downgrade in a mixed support scenario

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#58]
> A DPoP-bound access token must be sent in the Authorization header with the prefix DPoP. For such an access token, a resource server MUST check that a DPoP header was received in the HTTP request, check the header's contents according to the rules in (#checking), and check that the public key of the DPoP proof matches the public key to which the access token is bound per (#Confirmation).

In my opinion an RS must also check the presence and value of the DPoP Proof JWT when an Access Token (introspected, JWT-verified, or otherwise...) contains `cnf` with `jkt` so that simple use of Bearer scheme with a constrained token value doesn't end up returning a protected resource.

**Comment by panva** [comment]
Let me clarify the intent of this issue.

The intent is NOT to have existing Resource Servers that do not support DPoP check for `jkt` presence.

But, given an RS supports both Bearer and DPoP schemes for some resources (e.g. during a gradual DPoP rollout based on User-Agent's supporting WebCryptography API using DPoP, legacy not) - if a malicious actor gets hold of a DPoP Access Token it should not be able to use it at the RS just because it would replace the `DPoP` scheme with `Bearer`. Therefore i feel like we need to extend the `Resource Access (Proof of Possession for Access Tokens)` section with a numbered list steps guidance and mention that when both DPoP and Bearer scheme is supported the RS must not only rely on the use of `DPoP` scheme but also check whether the token's confirmation methods include DPoP.

**Comment by b---c** [comment]
Putting aside for the time being the question of where it'd go in the document, I think I now understand and aggree with what you are suggesting. Which could be (correct me if I'm still wrong though) to explicitly state that an RS that is supporting both Bearer and DPoP schemes simultaneously needs to update its Bearer token evaluation functionality so as to reject tokens that are dpop bound (via `cnf.jkt` or implementation specific means agreed on by AS and RS).  I'm that situation should just be a a rejection, however, rather than a different signal to kickstart the DPoP verification stuff.

**Comment by panva** [comment]
Correct, a rejection.

**Comment by b---c** [comment]
11b0e24e40b3e75934c24aef72cba2da41beb560 addresses this (I hope anyway)
