### ISSUE TITLE
define max length of dpop-nonce

### ISSUE THREAD

**Issue by panva** [danielfett/draft-dpop#92]
A client implementation may get its cache, used for mapping the last received nonce per endpoint/hostname, exhausted unless we define a maximum length of a dpop-nonce. It is currently defined as `1*NQCHAR`.

I propose that we define both minimum and maximum octet length, e.g. how PKCE code verifier is defined so that clients may safely ignore dishonest's AS/RS nonces are that excessively large.

**Comment by bc-pi** [comment]
"per endpoint/hostname" - I was under the impression that a client would keep and use the last received nonce for whatever path under a particular host. Do you interpret -04 differently? I think we'd need to address that before talking about nonce size.

**Comment by panva** [comment]
> "per endpoint/hostname" - I was under the impression that a client would keep and use the last received nonce for whatever path under a particular host. Do you interpret -04 differently? I think we'd need to address that before talking about nonce size.

Client software may consume AS responses as well as issue RS requests. Both of which may be multiple. So you need to keep track of each issuer's last, e.g. per discovery document, as well as each resource server, or its particular endpoint)

**Comment by panva** [comment]
> Do you interpret -04 differently?

I don't interpret -04 this way, hence #88. Nevertheless it is(was?) my expectation of -05 after the discussion at #osw6.

It's just that as I was writing the client implementation I realized the different tricks I myself used to pull with my past deployments which made it seem like the userinfo endpoint was a part of the AS but was infact served by a separate system - on the same host, but without access to the AS secrets. Likewise how different RS endpoints may be organized under the same host but come with different security requirements, may come from different teams, and maybe not share the point of requiring nonce altogether, or have a different mechanism/secret for its generation, or have a different duration of its validity.

So I ended up with per origin+pathname cache key for last nonces. Maybe it's silly, you tell me, maybe it's not. Ideally this would be host based but I'm just getting ready for the different wacky realities I have myself encountered.

**Comment by bc-pi** [comment]
I wouldn't say it's silly. We just seem to be thinking about things differently. Defining a challenge/response kind of thing is much more nuanced and difficult than it seems like it'd be. Which is why I pushed back on it for a long time.  But here we are... I'd like to get to something in the draft that's simple and efficient and implies implementations which are the same. Like where the client can just use the last nonce received per host and things will work (most of the time at least). I'm not sure how to get there though. Or if it's actually possible.

**Comment by panva** [comment]
If it was called out to be like so it'd resolve #88 for sure and I still think it wouldn't hurt to define both min and max nonce octet-length.

**Comment by bc-pi** [comment]
Tried to split the first part of the conversation to #88. On the mix/max size - keeping the nonce size reasonable is worthwhile but, honestly, I'm always really reluctant to place arbitrary hard limits on things like that. And there's some incentive already to keep it smallish as this stuff is all going in HTTP headers. But I dunno. What numbers would you go with?

**Comment by panva** [comment]
Min ?? upto and including 128?

**Comment by selfissued** [comment]
None of the OAuth parameter in https://datatracker.ietf.org/doc/html/rfc6749#appendix-A have maximum sizes defined.  Following that precedent, I propose that we do the same.

**Comment by panva** [comment]
@selfissued following the precedent of code_verifier and the reasons presented I think this should be done. Even per hostname cache space could easily be exhausted leading to DoS.

**Comment by selfissued** [comment]
The good news, @panva, is that the server is entirely in control of how much it stores or doesn't.  The server creates the nonces and so is in control of their size.  The server is free to dispose of cached nonce state at any time, since if the client tries to use a nonce that the server doesn't recognize, the server can generate a new nonce on the fly and ask the client to use it.  As discussed in issue #88, any mismatched nonce situation is self-correcting.

There's also another reason we want servers to be able size the nonces they generate as they choose.  If the server encrypts the nonce content to itself, the nonce can be fully self-describing and contain all the state needed to use it.  By allowing the nonces to be big enough to contain encrypted content, it can mean that the server doesn't have to store them at all!  @will-bartlett may be able to add more detail to this description, as I believe we use this technique today.

**Comment by panva** [comment]
I'm not talking about an issue with the servers that generate the nonces but rather clients that are instructed to talk to a number of ASs and likewise a number of RSs. 

I understand that nonce loss is self-correcting but i believe it's unreasonable to have uncapped server provided values at play.

**Comment by selfissued** [comment]
First, I expect that the vast majority of clients will talk to exactly one AS and one RS.  Among those that talk to multiple, I expect that the vast majority of those will talk to at most a fixed small number of them, almost certainly less than 10.  I'm not aware of realistic deployments in which a client will talk to an unbounded number of ASs and RSs.

But again, just as for servers, should storing nonce values become a burden for clients, they're free to discard them.  They will dynamically get a new nonce value to use when they try a request without one.  This is another situation that's self-correcting.

I really don't see that there's an actual problem to solve here in practice.  Or is there something I'm missing here?

**Comment by panva** [comment]
> First, I expect that the vast majority of clients will talk to exactly one AS and one RS. Among those that talk to multiple, I expect that the vast majority of those will talk to at most a fixed small number of them, almost certainly less than 10. I'm not aware of realistic deployments in which a client will talk to an unbounded number of ASs and RSs.

I don't think it's responsible to make blank statements like so and completely dismiss an issue. Constrained client environments and software exists.

> But again, just as for servers, should storing nonce values become a burden for clients, they're free to discard them. They will dynamically get a new nonce value to use when they try a request without one. This is another situation that's self-correcting.

I can imagine (altho have no actual hard evidence of) even echoing back a large value might be an issue in very memory constrained software so self-correcting won't work. Not to mention that always relying on self correcting / echoing back is very inefficient.

Once #88 is resolved based on our #osw6 discussion the guidance could either admit this inefficient shortcoming if a server chooses to use irrationally long nonces and the client cannot keep them around or put a sensible hard limit on the nonce value length that would allow for usage of encrypted values that keep their own state but not be completely unlimited.

Personally I think such server nonce design is a waste of computational cycles and client cache memory but that's for each implementer to judge on their own and not my business.

**Comment by will-bartlett** [comment]
As @selfissued says, the other OAuth fields don't have length limitations. A client with strict memory usage requirements can't implement OAuth with arbitrary unknown servers, because it can't call Json.Parse on the OAuth HTTP response from /token. Such a client is only able to implement OAuth with known servers, which provide additional guarantees above and beyond the standard w.r.t the maximum size of the OAuth response. I think this status quo is reasonable and would prefer to continue it.

With that in mind, if there is a desire to limit, 128 is too low a value. Microsoft uses timestamp based nonces in some scenarios already, in two variations - a symmetric (HMAC) nonce and an asymmetric (JWS) nonce. These are ~110 and ~600 bytes today. We've had some discussions about converting the large 600 byte JWS nonce from JSON to CBOR to make it smaller, but it's not really a problem in practice today.

In detail, these nonces are simply signed timestamps. They are not actually encrypted. You can actually get a sym nonce today by POSTing grant_type=srv_challenge to https://login.microsoftonline.com/common/oauth2/token - you'd get a value like AwABAAAAAAACAOz_BAD0_8KS8AJnLq4xCHg0ZNBqYiYeMwbtDmXkWxmCSlBq0bq2GQSpQCtowenf9ye7NOHitSho46WkQrHOr-1OWPPUTtQgAA. An asmy nonce is a little bit more complex to retrieve, but I've pulled one from the test environment - it is "O.eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InBxb2VhbWIyZTVZVnpSNl9ycUZwaUNyRlpndyJ9.eyJhdWQiOiJ1cm46bWljcm9zb2Z0OnJ0OmNoYWxsZW5nZSIsImlzcyI6Imh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImlhdCI6MTY0MzgyMzg2MCwibmJmIjoxNjQzODIzODYwLCJleHAiOjE2NDM4MjQxNjB9.B79d8qeHh2rw5DpLZAyUqkeaJfT8C5mXqmlcHRn8I4LtSUGT6E36qJS8X2T4_7IFVooWcK0nMdGwR7pDBaIr7jUfRDNsRPXbqjn3YwVEyblNQyxnAqxlGs3CdBpN9eT_82qCByNa93LaapH-bjHmjxdr56X4x_lEOmKRcRL8Rfo3UMdGiN0M5ZTFzQvOeezgkIMIQwnddJkj_Ap_q0meb66Mt8QfG2tjNUMDojlvUFUWY32_pBdnMX9gNmQMavrROVuvpkrjz28Dg7Psiw8dcbkG5_gzILdH_BEYOCdMgckuCdL6jH0P_VZaGhER8VdGQmtzzkUQRftER2FCnb_yCA" - that it, is it a prefix "O." followed by a JWS like {"typ":"JWT","alg":"RS256","x5t":"pqoeamb2e5YVzR6_rqFpiCrFZgw"}
{"aud":"urn:microsoft:rt:challenge","iss":"https://login.microsoftonline.com","iat":1643823860,"nbf":1643823860,"exp":1643824160}.<sig>.

As @selfissued says, the way we use these nonces at Microsoft is not by storing them - the nonces are self-describing. The STS or RP looks up the key using the "x5t", verifies the signature, and then compares the "iat" to the current server time, and accepts the JWT if it is within a short time window of the current server time.
